---
title: "t-SNE and UMAP Analysis"
author: "Kerem Uzel"
date: "2023-11-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(umap)
library(Rtsne)
library(tidyverse)
```

```{r}

# Load population data
population_names <- read.csv('oryx_pop_info_sorted_46_final.txt', sep='\t', header=TRUE)

# Load the covariance matrix
filename <- 'oryx_0.5xyh.cov'
cov_mat <- as.matrix(read.csv(filename, sep=' ', header=FALSE))

# Define number of principal components for UMAP and t-SNE calculations
n_pc <- 5

# Define parameter range for t-SNE
perplexity_values <- c(3,5,10,15)

# Define parameter space for UMAP
mindists <- c(0.001, 0.01, 0.1, 0.5)
n_neighbors_nums <- c(5, 10, 20)

```

```{r}
# PCA calculation
pca_result <- prcomp(cov_mat, scale. = TRUE)
principal_components <- pca_result$x[, 1:n_pc]

# Data structure for results
Data_Struct <- population_names
```

```{r}
for (perp in perplexity_values) {
  set.seed(111)
  tsne_result <- Rtsne(principal_components, perplexity=perp, is_distance=FALSE)
  Data_Struct[[paste0('tSNE-1 perp', perp)]] <- tsne_result$Y[,1]
  Data_Struct[[paste0('tSNE-2 perp', perp)]] <- tsne_result$Y[,2]
}

```

```{r}
set.seed(111)
for (nn in n_neighbors_nums) {
  for (mind in mindists) {
    set.seed(111)
    umap_result <- umap(principal_components, n_neighbors=nn, min_dist=mind)
    Data_Struct[[paste0('UMAP-1 numn', nn, ' mindist', mind)]] <- umap_result$layout[,1]
    Data_Struct[[paste0('UMAP-2 numn', nn, ' mindist', mind)]] <- umap_result$layout[,2]
  }
}

```

```{r}
# Create the plots
plot_list <- list()
row_index <- 1

# t-SNE plots
for (perp in perplexity_values) {
  x_col_name <- paste0('`tSNE-1 perp', perp, '`')
  y_col_name <- paste0('`tSNE-2 perp', perp, '`')
  tsne_plot <- ggplot(Data_Struct, aes_string(x=x_col_name, y=y_col_name, color='Population')) +
    geom_point() +
    theme_minimal() +
    labs(title=paste0('tSNE / Perplexity = ', perp))
  plot_list[[row_index]] <- tsne_plot
  row_index <- row_index + 1
}


# UMAP plots
for (nn in n_neighbors_nums) {
  for (mind in mindists) {
    x_col_name <- paste0('`UMAP-1 numn', nn, ' mindist', mind, '`')
    y_col_name <- paste0('`UMAP-2 numn', nn, ' mindist', mind, '`')
    umap_plot <- ggplot(Data_Struct, aes_string(x=x_col_name, y=y_col_name, color='Population')) +
      geom_point() +
      theme_minimal() +
      labs(title=paste0('UMAP / n_neighbours = ', nn, ', min_dist = ', mind))
    plot_list[[row_index]] <- umap_plot
    row_index <- row_index + 1
  }
}


# Display the plots
cowplot::plot_grid(plotlist = plot_list, ncol = length(n_neighbors_nums) + 1)

```


## Including Plots

You can also embed plots, for example:

```{r}
# Combine all plots into a single plot object
combined_plot <- cowplot::plot_grid(plotlist = plot_list, ncol = length(n_neighbors_nums) + 1)

# Save the combined plot
ggsave(paste0(filename, '_Top', n_pc, 'PCs_R.png'), plot = combined_plot, width = 20, height = 20, dpi = 100)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
